### ISSUE TITLE
Q: Way to Stop a VM?

### ISSUE THREAD

**Issue by icosahedron** [containers/krunvm#17]
Is there a way to run a VM headless and stop the VM without having to exit the process that was started by the VM? Without having to delete it? Maybe I missed it in the docs.

**Comment by slp** [comment]
For the sake of keeping it as simple as possible, krunvm does not support managing microVM instances in the background, thought it can be combined with tools such as `tmux` to achieve something close to that.

**Comment by icosahedron** [comment]
Thanks. I just wanted to make sure I hadn’t missed something.

tmux is great for scenarios like this.
