### ISSUE TITLE
PATH not used to start command

### ISSUE THREAD

**Issue by c3d** [containers/krunvm#20]
Running the following shows an example of the problem:

```
% krunvm start fedora-rawhide /bin/ls -- -l /bin/bash
-rwxr-xr-x 1 root root 1433752 Jul 20 22:00 /bin/bash
% krunvm start fedora-rawhide /bin/bash -- -c 'echo $PATH'
/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
% krunvm start fedora-rawhide bash
```

The last command does not succeed. You need to pass `/bin/path` for it to work.

Note that this is somewhat inconsistent with `podman` usage for example, where `podman run -it ubi8 bash` works.

**Comment by slp** [comment]
This has been fixed in `libkrun 1.3.0` / `krunvm 0.2.1`. Please let me know if the problem persists.
