### ISSUE TITLE
krun lib dependency ?

### ISSUE THREAD

**Issue by setop** [containers/krunvm#29]
using `make` or `cargo build --release`, I get an error `/usr/bin/ld: cannot find -lkrun`.

I don't get where dependency comes from : os (apt) or rust (cargo).

Any idea ?

**Comment by slp** [comment]
krunvm needs to link against [libkrun](https://github.com/containers/libkrun), which is a dynamic library. I'm aware that libkrun is packaged in Fedora Rawhide and OpenSUSE, but I don't know about other distros.

**Comment by setop** [comment]
I've seen it's in rust but not available on crates.io.
So I added its git repo to the cargo.toml file.
It kinda works but then I have issue compiling librun : something about init binary that is not found.
I have to work on it...
