### ISSUE TITLE
verbosity option doesn't seem to take effect

### ISSUE THREAD

**Issue by dsilvasc** [containers/krunvm#49]
`krunvm -v create ...` (or `-vvvv`) doesn't seem to do anything.  Searching the repo I don't see it calling `krun_set_log_level`.

**Comment by mtjhrc** [comment]
Yes, it is not implemented. This issue is a duplicate of #22. I plan to take a look at this.

**Comment by dsilvasc** [comment]
ah, sorry I didn't notice that one.  Closing in favor of https://github.com/containers/krunvm/issues/22
