### ISSUE TITLE
networking

### ISSUE THREAD

**Issue by tcurdt** [containers/krunvm#6]
Is there a way to connect multiple VMs into a cluster?
Some more information on the networking would be great.

**Comment by slp** [comment]
krunvm uses [libkrun](https://github.com/containers/libkrun) 's networking capabilities, which are based on TSI (Transparent Socket Impersonation). You can find some information about it libkrun's project page, and in the slides 12-16 of [this presentation](https://static.sched.com/hosted_files/devconfcz2021/b9/libkrun%20Virtuailzation-based%20isolation%20for%20your%20workloads.pdf).

What are the network requirements of the cluster? Are the nodes going to be running on different krunvm instances on the same Host? If that's the case, and the cluster service is able to differentiate each node by having it using a different service port, you might be able to use krunvm's port mapping feature to configure a different port on each node.

If the cluster requires each node to have a different IP address, and those are going to be run on different instances on the same Host, that'd be a use case that's not supported by krunvm out-of-the-box. But, there's probably still the possibility of making it work by manually configuring a vethX/vethY pair, adding vethX to a network bridge on the Host, and moving vethY to an independent network namespace. Then you'll need to assign an IP to vethY, and run krunvm on this network namespace.

If you could give me more details about this kind of cluster, I would like to give it a try myself.

**Comment by tcurdt** [comment]
I often use vagrant to spin up 2-3 VMs (on one host) that share a private network to test things. From the README it was quite clear if krunvm could be used to do a similar thing. Hence I opened the issue :)

Wishlist: Two machines on one host. Both sharing a private network and having an internal IP each. And also some way from the host to reach the VMs via sockets (port forwarding or something).

I'll read up on TSI - but wanted to leave this here first.

**Comment by slp** [comment]
Being completely honest, I don't krunvm is good fit for that use case. Even after solving the networking part using network namespaces, the customizations in the kernel shipped with libkrunfw, and the virtio-fs-based root filesystem may lead to issues that are not strictly related to the applications being tested.

I think QEMU is better suited for that use case. If you want a lighter machine model, you could give a try to the `microvm` machine type. Some distributions even ship a specialized version of QEMU with just that machine type.

**Comment by tcurdt** [comment]
QEMU? That didn't even cross my mind yet.
That might even allow for some more flexibility in architectures.
But probably not the lightweight alternative to virtualbox I was hoping for.

**Comment by slp** [comment]
While the "standard" QEMU build is quite large and has many dependencies, a microvm-specialized build should be quite lightweight.

I've just checked (using krunvm! ;-) the version that Ubuntu ships in the `qemu-system-x86-microvm`:

```
root@ubuntu-test:~# ldd /usr/bin/qemu-system-x86_64-microvm 
	linux-vdso.so.1 (0x00007fffafda5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f434f9cc000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f434f925000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f434f920000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f434f913000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f434f7ea000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f434f69b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f434f67e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f434f65b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f434f469000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f434ff82000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f434f3f6000)
root@ubuntu-test:~# ls -l /usr/bin/qemu-system-x86_64-microvm 
-rwxr-xr-x. 1 root root 5809120 Feb 10 14:17 /usr/bin/qemu-system-x86_64-microvm
```

Not bad, I'd say.
