### ISSUE TITLE
Update for Fedora Asahi Remix 40

### ISSUE THREAD

**Issue by LukeShortCloud** [containers/krunvm#60]
The Fedora Copr builds of `krunvm` for Fedora Asahi Remix currently only has builds for Fedora 38 and 39. Would it be possible to enable the build for Fedora 40 now that it has been released?

https://fedoramagazine.org/fedora-asahi-remix-40-is-now-available/

```
$ sudo dnf copr enable slp/asahi-krun
```
```
Do you really want to enable copr.fedorainfracloud.org/slp/asahi-krun? [y/N]: Y
Error: It wasn't possible to enable this project.
Repository 'fedora-40-aarch64' does not exist in project 'slp/asahi-krun'.
Available repositories: 'fedora-38-aarch64', 'fedora-38-i386', 'fedora-39-x86_64', 'fedora-39-i386', 'fedora-38-x86_64', 'fedora-39-aarch64'
```

**Comment by slp** [comment]
The idea is to use [krun](https://github.com/slp/krun) instead of `krunvm` on Asahi. You might find this guide useful until the packages land in the distro: https://gist.github.com/teohhanhui/042a395010d9946ceee14768736e3780

**Comment by LukeShortCloud** [comment]
Thanks for the info! I see, they are both separate yet related projects.

From the [guide](https://copr.fedorainfracloud.org/coprs/teohhanhui/asahi-krun) you linked, I found this Fedora Copr to to have `krun` for Fedora 39 and 40.

```
$ sudo dnf copr enable teohhanhui/asahi-krun
```

What do you think about removing your old Copr to avoid confusion? It has packages for Fedora 38 and 39 but Fedora 38 is end-of-life and the other Copr has updated packages for Fedora 39 as well. Otherwise, they provide the same packages.

https://copr.fedorainfracloud.org/coprs/slp/asahi-krun/packages/
https://copr.fedorainfracloud.org/coprs/teohhanhui/asahi-krun/packages/
